### ISSUE TITLE
Converting this repo to an org

### ISSUE THREAD

**Issue by alexindigo** [form-data/node-form-data#134]
@felixge Looks like life is getting back to FormData, and it's being an org would allow it to be more flexible and (hopefully) improve responsiveness to issues. Thank you.

**Comment by felixge** [comment]
Sure, where should this go? github.com/node-form-data/node-form-data ?

**Comment by alexindigo** [comment]
Thanks. Maybe just `form-data` – to match npm package name, but either is fine.

**Comment by felixge** [comment]
@alexindigo i.e. github.com/form-data/form-data ?

It's up to you, as far as I'm concerned this is your project by now :)

**Comment by alexindigo** [comment]
Yes `github.com/form-data/form-data`. Thank you. :) 
And your spirit is still alive here. :)

**Comment by alexindigo** [comment]
@felixge this – https://github.com/form-data

**Comment by felixge** [comment]
@alexindigo https://github.com/form-data/node-form-data - I'll leave it to you if you want to rename the repo further.

**Comment by alexindigo** [comment]
Thank you @felixge.
